stages:
  - build
  - test
  - deploy

Build-Test:
  stage: build
  tags:
  - build
  script:
   
    - ng build

Lint-Test:
  stage: test
  tags:
  - test
  script:
   
    - ng lint
    
Deploy:
  stage: deploy
  tags:
  - deploy
  script:
    
    - ng build
    - cd dist
    - mv angapp angappVersion3
    - git init
    - git pull http://shaikerss:R!kons250394@gitlab.com/appo2/angapprepo
    - git config --global user.name "shaik"
    - git config --global user.email "time-sr@hotmail.com"
    - git add -A
    - git commit -m "Commit New Version"
    - git branch -m main
    - git push --set-upstream http://shaikerss:R!kons250394@gitlab.com/appo2/angapprepo main
     
  artifacts:
    paths:
      - /home/gitlab-runner/builds/xdKvHweH/0/shaikerss/angapp/dist
    expire_in: 1 week
