stages:
  - build
  - test
  - deploy

Build-Test:
  stage: build
  tags:
  - build
  script:
    - npm install
    - ng build
    - aws --version

Lint-Test:
  stage: test
  tags:
  - test
  script:
    - npm install
    - ng lint
    
Deploy:
  stage: deploy
  tags:
  - deploy
  script:
    - npm install
    - ng build
    - cd dist
    - git init
    - mv angapp artifacts_stage
    - git pull http://$GITLAB_USER_NAME:$GITLAB_USER_PASSWORD@gitlab.com/appo2/angapprepo
    - git config --global user.name "shaik"
    - git config --global user.email "time-sr@hotmail.com"
    - rm -rf artifacts.zip
    - mv artifacts $VERSION_NUMBER
    - mv artifacts_stage artifacts
    - zip artifacts artifacts
    - git add -A
    - git commit -m "Commit New Version"
    - git branch -m main
    - git push --set-upstream http://$GITLAB_USER_NAME:$GITLAB_USER_PASSWORD@gitlab.com/appo2/angapprepo main

    
   
    
     
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
