stages:
  - build
  - test

build-Test:
  stage: build
  tags:
  - build
  script:
    - npm install
    - ng build

Lint-Test:
  stage: build
  tags:
  - build
  script:
    - npm install
    - ng lint
