stages:
  - build
  - test
  - deploy

Build-Test:
  stage: build
  tags:
  - build
  script:
    - npm install
    - ng build

Lint-Test:
  stage: test
  tags:
  - test
  script:
    - npm install
    - ng lint
    
Deploy:
  stage: deploy
  tags:
  - deploy
  script:
    - npm install
    - ng build
    - git add remote origin git@gitlab.com:appo2/angapprepo.git
    - git pull origin main
    - git push origin main
  artifacts:
    paths:
      - /home/gitlab-runner/builds/xdKvHweH/0/shaikerss/angapp/dist/angapp 
    expire_in: 1 week
