stages:
  - build
  - test
  - deploy

Build-Test:
  stage: build
  tags:
  - build
  script:
    - npm install
    - ng build

Lint-Test:
  stage: test
  tags:
  - test
  script:
    - npm install
    - ng lint
    
Deploy:
  stage: deploy
  tags:
  - deploy
  script:
    - npm install
    - ng build
    - cd dist
    - mv angapp artifacts
    - git init
    - git pull http://$GITLAB_USER_NAME:$GITLAB_USER_PASSWORD@gitlab.com/appo2/angapprepo
    - git config --global user.name "shaik"
    - git config --global user.email "time-sr@hotmail.com"
    - rm -rf 4 artifacts Version_5 Version_6 Version_8 angappVersion1 angappVersion2 angappVersion3
    - git add -A
    - git commit -m "Commit New Version"
    - git branch -m main
    - git push --set-upstream http://$GITLAB_USER_NAME:$GITLAB_USER_PASSWORD@gitlab.com/appo2/angapprepo main
   
    
     
  artifacts:
    paths:
      - /shaikerss/angapp/dist/
    expire_in: 1 week
