stages:
  - build
  - test
  - deploy

Build-Test:
  stage: build
  tags:
  - build
  script:
    - npm install
    - ng build

Lint-Test:
  stage: test
  tags:
  - test
  script:
    - npm install
    - ng lint
    
Deploy:
  stage: deploy
  tags:
  - deploy
  script:
    - npm install
    - ng build
    - git config --global user.name "shaik"
    - git config --global user.email "time-sr@hotmail.com"
    - mv dist distV1
    - git add -A
    - git commit -m "uploadversion 1"
    - git push http://shaikerss:R!kons250394@gitlab.com/appo2/angapprepo  HEAD:main
  artifacts:
    paths:
      - /home/gitlab-runner/builds/xdKvHweH/0/shaikerss/angapp/distV1
    expire_in: 1 week
